mysql:
  rootPassword: "Root Password here..."
  user: nextcloud
  password: "User Password here..."
  database: nextcloud

php:
  repository: "nextcloud"
  tag: "official-fpm-alpine"
  persistentSubpaths:
  - apps
  - config
  - data
