airflow:
  image:
     repository: airflow-docker-local
     tag: 1
  executor: Kubernetes
  service:
    type: LoadBalancer

  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: True
    AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: False
    AIRFLOW__CORE__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__FERNET_KEY: -VPrAtf3PunVqdBKdURvTnbn0VYOJfBqivkz9N3K2qo=
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://developer:developer@ore.crca4ssbk7go.eu-west-1.rds.amazonaws.com/ore?connect_timeout=10
    AIRFLOW__CELERY__RESULT_BACKEND: postgresql://developer:developer@ore.crca4ssbk7go.eu-west-1.rds.amazonaws.com/ore?connect_timeout=10
    AIRFLOW__CELERY__BROKER_URL: redis://:airflow@airflow-redis-master:6379/0
    AIRFLOW__CORE__LOAD_EXAMPLES: False

    # Remote Logging
    AIRFLOW__CORE__REMOTE_LOGGING: False

    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: True
    AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC: 30
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: airflow-docker-local
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 1
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: IfNotPresent
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: airflow-logs
    AIRFLOW__KUBERNETES__NAMESPACE: airflow
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: True
    AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: '{\"_request_timeout\":[60, 60]}'

persistence:
  enabled: false

logsPersistence:
  enabled: false


workers:
  enabled: true

postgresql:
  enabled: false

redis:
  enabled: true

dags:
  git:
    url: ssh://git@github.com:apache/airflow.git
    repoHost: github.com
    secret: airflow-git-keys
    privateKeyName: id_rsa

    gitSync:
      enabled: true
      refreshTime: 60

externalDatabase:
  type: postgres
  host: ore.crca4ssbk7go.eu-west-1.rds.amazonaws.com
  port: 5432
  database: ore
  user: developer
  passwordSecret: "airflow-postgres-password"
  passwordSecretKey: "developer"


  git_repo and git_branch and git_dags_folder_mount_point